# Generated by Django 5.1 on 2024-09-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
